common: &common
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5
  min_messages: warning

development:
  <<: *common
  database: rental_agency_development

test:
  <<: *common
  database: rental_agency_test

production:
  <<: *common
  database: rental_agency_production
